### ISSUE TITLE
Maunder's callsign is misaligned on the roster

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#22] opened 2015-04-02 23:09 UTC
It seems like his name and callsign are using two different alignment modes because they are offset from each other.

It might be due to his massive image of a rank icon.

![image](https://cloud.githubusercontent.com/assets/11630560/6975568/cafe3b84-d96b-11e4-9ef6-48babfe8617c.png)

**Comment by jonpas** [comment] 2015-04-02 23:12
Looking all good on my side. Can you do CTRL+F5 (clear cache) and see if that fixes it? Also what browser are you using? I guess this is UCOM roster page?

**Comment by codethirteen** [comment] 2015-04-02 23:44
It's an image alignment issue that I fixed on my local dev environment. Problem is we can't target that specific image (and staff sergeant and above does it too) without a script to recognize it. The fix is vertical-align: middle on the image and increasing line-height to be more than the tallest image. That will center everything out.

**Comment by codethirteen** [comment] 2015-04-02 23:44
The fix is `vertical-align: middle` on the image.

**Comment by SyMP2005** [comment] 2015-04-03 06:54
Same for Joel Restrepo's!

**Comment by jonpas** [comment] 2015-04-03 10:08
Assigning to you @codethirteen since you know what the problem is.

**Comment by codethirteen** [comment] 2015-04-03 13:44
Work browser(s) - could see issue. Home browser(s) - Nada, all looks good. 

I can't see a fix in our Github commit history, so that's strange. Someone reply here if they still see this issue please.

**Comment by jonpas** [comment] 2015-04-03 14:11
Uhm, no one commited a fix so. :P

**Comment by codethirteen** [comment] 2015-04-03 14:17
lol, check style.css file for last modification time... looks like someone added line-height directly, cos it doesn't show in release branch. :P

**Comment by jonpas** [comment] 2015-04-03 14:19
Nope, whenever something gets committed to GitHub it will drop all local changes in favor of GitHub build, on both release and master.

**Comment by codethirteen** [comment] 2015-04-03 14:26
OK I need coffee, I coulda sworn I didn't see the `line-height` for `main` class ten minutes ago, now I do and it's always been there... ok well this issue can be closed until someone brings it up again.

**Closed as completed by codethirteen** 2015-04-03 14:26 UTC
Labels: bug, [Web]

**Comment by jonpas** [comment] 2015-04-03 14:29
So what now? I am confused, does it work or is it random or?

**Comment by codethirteen** [comment] 2015-04-03 14:35
No I am not sure if this was ever a real issue. I used my browserstack.com account this morning to check it on a lot of different browsers, and could not see the problem. 

So you were most likely correct in your initial reply: It was probably a caching issue, but clearing cache did not fix it for me at the time. At work I'm behind government firewalls and proxies, so that could have caused it for me. 

If it reappears we can reopen this issue.

**Comment by codethirteen** [comment] 2015-04-03 14:54
I am seeing this on the unit rosters, not the main roster. So I'm moving this over to the website's issues and keeping this one closed.
