### ISSUE TITLE
Rank Pictures wrong

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#4] opened 2015-03-24 12:52 UTC
**Explanation:** Happens only on Safari browser
**Solution:** Clear Safari cache (http://www.imore.com/how-clear-stored-website-data-ios-7-safari).

---

On the ranks page under reference:

"Colonel in chief" has a "sergeant major" insignia

"Lance corporal" has a "sergeant major of the force" insignia

**Comment by MattLightfoot** [comment] 2015-03-24 12:55
Not for me chap can you reproduce it? and take screenshots chap?

**Comment by codethirteen** [comment] 2015-03-24 13:00
Checked both live and production sites, and I cannot see this either. My view:

![cic](https://cloud.githubusercontent.com/assets/21903/6802145/dcb1dbe6-d1fb-11e4-8cc8-331e1a5c4fb9.jpg)
![lcpl](https://cloud.githubusercontent.com/assets/21903/6802146/dcb57116-d1fb-11e4-92ca-7f9a8b6e2f32.jpg)

**Comment by assaultboy** [comment] 2015-03-24 13:53
Maybe it's a mobile device issue?

http://i.imgur.com/KohlEmf.jpg?1
http://i.imgur.com/0UptMe2.jpg?1

**Comment by assaultboy** [comment] 2015-03-24 14:00
I don't know if you changed anything but now They are both fixed but brigadier gen is retired and pvt is a 1lt

**Comment by codethirteen** [comment] 2015-03-24 14:01
We don't have any code in place that changes the website for mobile users, at this point. I have an AT&T iPhone 6+, but I'm not seeing this issue on that either. But that is strange...

**Comment by assaultboy** [comment] 2015-03-24 14:06
Just checked with a proper desktop and it is correct for that computer. So it must be something unique to my phone?

**Comment by codethirteen** [comment] 2015-03-24 14:09
Actually we're on TS discussing it. I see it on Safari on iOS, but nothing else. I normally use Chrome on iOS, so I was not seeing it. I don't know why it's doing it, but I'll mark this as a bug now I've been able to replicate it. Thanks!

**Comment by codethirteen** [comment] 2015-03-24 14:13
So I cleared my safari cache (http://www.imore.com/how-clear-stored-website-data-ios-7-safari) and it fixes this issue for me. Can you confirm it does the same for you?

**Comment by assaultboy** [comment] 2015-03-24 17:06
Clearing the cache does fix the problem.

**Comment by jonpas** [comment] 2015-03-24 17:35
Good to hear, @codethirteen anything we can do about it or is it Safari bug?

Marked it as a question for further reference and posted the answer on top of first comment.

**Comment by codethirteen** [comment] 2015-03-24 21:52
No not a bug, just a local user issue. Probably due to the recent rank changes we made.

**Closed as completed by codethirteen** 2015-03-24 21:52 UTC
Labels: question, [Web]

**Comment by jonpas** [comment] 2015-03-24 22:13
Okay, good find then!
