### ISSUE TITLE
Combat Media Ribbon not displaying for multiple ribbons

### ISSUE THREAD

**Issue by ghost** [usecforce/USEC_IssuesWiki#44] opened 2015-05-09 11:53 UTC
See here: http://www.usecforce.com/profile/?id=3637

Everyone else who has one ribbon works just fine, but Cole has multiple, and a missing file.

**Comment by codethirteen** [comment] 2015-05-09 11:58
Confirmed, test account has the same issue when awarded multiple times. http://www.usecforce.com/profile/?id=3668

**Comment by jonpas** [comment] 2015-05-09 15:14
That is because we only have 1 version of the ribbon and the ribbon is marked as "can be awarded multiple times", as you can see if you check the link to them they are as follows:
- 1 ribbon: `comp_screenshot.png`
- 2 ribbons: `comp_screenshot_no2.png`
- 3 ribbons: `comp_screenshot_no3.png`
- 4 ribbons: `comp_screenshot_no4.png`

We can either make symlinks with new names or mark it as only one-time award, but then I am not sure if you can actually award it multiple times, I will check.

**Comment by jonpas** [comment] 2015-05-09 15:33
Temporarily fixed by disabling multiple awards, we should think of having different images though, or even better adjust in website code so we can have it that the ribbon can be set to multiple but still show the same picture, just more records.

Right now the multiple value can be `0` (multiple awards show as separate images) or `1` (multiple awards show as one image with variants with multiple records on mouse hover, meaning the image needs to have variants as shown in above comment). We could add if the value is `2` (multiple awards show as one, main image with multiple records on mouse hover, meaning there would be only one image shown for all variants). The only thing we would have to do is check if value is 2 then don't append `_noX` in the image name, should be easy.

Closing this issue as it's been fixed, feature request for third value of multiple awards will be posted on Website repo.

**Closed as completed** 2015-05-09 15:35 UTC
Labels: bug, [Web]
